projectgame/projectgame/urls.py
from django.contrib import admin
from django.urls import path, include
from . import settings
from django.contrib.staticfiles.urls import static
from django.contrib.staticfiles.urls import staticfiles_urlpatterns




urlpatterns = [
    path('admin/', admin.site.urls),
    path('', include('nonregister.urls')),
    path('user/', include('user.urls'))
] + static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

projectgame/user/urls.py
from django.urls import path
from . import views



urlpatterns = [
    # path('', views.homepage, name='home'),
    # path('login/', views.my_login, name='login'),
    # path('register/', views.register, name='register'),
    path('../gamedetail/', views.user, name='user')
    
]

projectgame/nonregister/models.py
from django.db import models
from distutils.text_file import TextFile
from numbers import Integral
from django.contrib.auth.models import User


# Create your models here.
class Regis(models.Model):
    fname = models.CharField(max_length=250, default="", editable=True)
    lname = models.CharField(max_length=250, default="", editable=True)
    username = models.CharField(max_length=50, default="", editable=True)
    password = models.CharField(max_length=50, default="", editable=True)
    email = models.CharField(max_length=50, default="", editable=True)


class Game_type(models.Model):
    type_name = models.CharField(max_length=255, default="", editable=True)
    
    def __str__(self):
        return self.type_name
    


    
class Game(models.Model):
    
    name = models.CharField(max_length=255, default="", editable=True)
    description = models.CharField(max_length=255, default="", editable=True)
    game_type_id = models.ForeignKey(Game_type, on_delete=models.PROTECT)
    developer = models.CharField(max_length=255, default="", editable=True)
    rating = models.CharField(max_length=255, default="", editable=True)
    release_date = models.DateTimeField()
    price = models.IntegerField()
    def __str__(self):
        return self.name


class Image(models.Model):
    
    game_id = models.ForeignKey(Game, on_delete=models.CASCADE)
    img_url = models.ImageField(upload_to='static/static_dirs/images/')
    def __str__(self):
        return self.game_id.name

    
    

class User_Game(models.Model):
   
    user_id = models.ForeignKey(User, on_delete=models.PROTECT)
    game_id = models.ForeignKey(Game, on_delete=models.CASCADE)
    purchased_date = models.DateField(auto_now=True)
    serial = models.CharField(max_length=255, default="", editable=True)

projectgame/user/models.py
from django.db import models

# Create your models here.

projectgame/user/views.py
from django.shortcuts import render

# Create your views here.
def user(request):
    return render(request, 'user/gamedtail.html')

projectgame/user/templates/user/gamedatailuser.html
{% extends 'base.html' %}
{% block  content%}
{% load static %}

<div class="container">       
    <div class="row shadow-sm p-3 mb-5 bg-white rounded justify-content-center">
        <img src="{{ img_pk.img_url.url }}" width="40%" class="d-block" alt="">
    </div>
    <div class="row shadow p-3 mb-5 bg-white rounded">
        <div class="col-md-3">
            <img src="{{ img_pk.img_url.url }}"  width="100%" class="text-center" alt="">
        </div>
        <div class="col-md-6 text-center">
            <p>{{ game_pk.name }}</p>
        </div>
        <div class="col-md-3 text-right">
            <h5 class="mx-4">{{ game_pk.price }}</h5>
        </div>
        <div class="col-md-4 mt-5 text-left">
            <b><h3 class="">About this game</h3></b>
        </div>
        <div class="col-md-4  mt-5 text-center">         
            <b><p class="text-center">Developer</p></b>
            <p class="text-center">{{ game_pk.developer }}</p>
            <b><p class="text-center">Tags</p></b>
            <p class="text-center">{{ game_pk.game_type_id.type_name}}</p>
            
        </div>
        <div class="col-md-4 mt-5">
            <b><p class="text-center">Serialnumber</p></b>
            <p class="text-center">{{ usergm.serial }}</p>
            <b><p class="text-center">Purchased Date</p></b>
            <p class="text-center">{{ usergm.purchased_date }}</p>
        </div>
        <div class=" col-md-12 m-2 my-1 mt-5 text-center">
            <b><p class="text-center">{{ game_pk.description }}</p></b>
        </div>   
        
    </div>
    <div class="row shadow-none p-2 mb-5 bg-light rounded"></div>
        <!-- <div class="col-md-3 text-center">
            <b><h3 class="">About this game</h3></b>
        </div>
        <div class="col-md-3 text-center">         
            <b><p class="text-center">Developer</p></b>
            <p class="text-center">{{ game_pk.developer }}</p>
            <b><p class="text-center">Tags</p></b>
            <p class="text-center">{{ game_pk.game_type_id.type_name}}</p>
        </div>
        <div class="col-md-3">
            <b><p class="text-center">Rating</p></b>
            <p class="text-center">{{ game_pk.rating }}</p>
            <b><p class="text-center">Release Date</p></b>
            <p class="text-center">{{ game_pk.release_date }}</p>
        </div>
        <div class=" col-md-12 m-2 my-1 mt-5 text-center">
            <b><p class="text-center">{{ game_pk.description }}</p></b>
        </div>    -->
    </div>         
</div>
{% endblock  %}

projectgame/user/templates/user/gamedtail.html
{% extends 'base.html' %}
{% block  content%}
{% load static %}

<div class="container">       
    <div class="row shadow-sm p-3 mb-5 bg-white rounded justify-content-center">
        <img src="{{ img_pk.img_url.url }}" width="40%" class="d-block" alt="">
    </div>
    <div class="row shadow p-3 mb-5 bg-white rounded">
        <div class="col-md-3">
            <img src="{{ img_pk.img_url.url }}"  width="100%" class="text-center" alt="">
        </div>
        <div class="col-md-6 text-center">
            <p>{{ game_pk.name }}</p>
        </div>
        <div class="col-md-3 text-right">
            <h5 class="mx-4">{{ game_pk.price }}</h5>
            
            
            {% if  perms.nonregister.add_user_game %}
                {% if user.is_superuser %}
                <a href= "{% url 'drop_game' game_pk.id %}"  class="btn btn-outline-dark my-1 bg-muted">ลบเกม</a>
                <a href= "{% url 'game_modify' game_pk.id %}"  class="btn btn-outline-dark my-1 bg-muted">แก้ไขเกม</a>
                {% elif user %}
                <a href= "{% url 'payment' game_pk.id %}"  class="btn btn-outline-dark my-1 bg-muted">Buynow</a>
                {% endif %}
            {% else %}
                <a href= "{% url 'login' %}"  class="btn btn-outline-dark my-1 bg-muted">Buynow</a>
            {% endif %}
        </div>
        <div class="col-md-4 mt-5 text-left">
            <b><h3 class="">About this game</h3></b>
        </div>
        <div class="col-md-4  mt-5 text-center">         
            <b><p class="text-center">Developer</p></b>
            <p class="text-center">{{ game_pk.developer }}</p>
            <b><p class="text-center">Tags</p></b>
            <p class="text-center">{{ game_pk.game_type_id.type_name}}</p>
        </div>
        <div class="col-md-4 mt-5">
            <b><p class="text-center">Rating</p></b>
            <p class="text-center">{{ game_pk.rating }}</p>
            <b><p class="text-center">Release Date</p></b>
            <p class="text-center">{{ game_pk.release_date }}</p>
        </div>
        <div class=" col-md-12 m-2 my-1 mt-5 text-center">
            <b><p class="text-center">{{ game_pk.description }}</p></b>
        </div>   
        
    </div>
    <div class="row shadow-none p-2 mb-5 bg-light rounded"></div>
        <!-- <div class="col-md-3 text-center">
            <b><h3 class="">About this game</h3></b>
        </div>
        <div class="col-md-3 text-center">         
            <b><p class="text-center">Developer</p></b>
            <p class="text-center">{{ game_pk.developer }}</p>
            <b><p class="text-center">Tags</p></b>
            <p class="text-center">{{ game_pk.game_type_id.type_name}}</p>
        </div>
        <div class="col-md-3">
            <b><p class="text-center">Rating</p></b>
            <p class="text-center">{{ game_pk.rating }}</p>
            <b><p class="text-center">Release Date</p></b>
            <p class="text-center">{{ game_pk.release_date }}</p>
        </div>
        <div class=" col-md-12 m-2 my-1 mt-5 text-center">
            <b><p class="text-center">{{ game_pk.description }}</p></b>
        </div>    -->
    </div>         
</div>
{% endblock  %}

projectgame/user/templates/user/payment.html
{% extends 'base.html' %}
{% block content %}
{% load static %}


<div class="col-md-12 order-md-1">
    <div class="row shadow-sm p-3 mb-5 bg-white rounded justify-content-center">
        <img src="{{ img_pk.img_url.url }}" width="40%" class="d-block" alt="">
    </div>
    <h1 class="mb-3 text-center">{{game_pk.name}}</h1>
    <img src="{{ image.image_url.url }}" class="rounded mx-auto d-block" style="width:100%">
    <form class="need-validation" novalidate>
    </form>
    <h3 class="mb-3">Payment</h3>
    <div class="form-check">
        <input class="form-check-input" type="radio" name="exampleRadios" id="exampleRadios1" value="option1" checked>
        <label class="form-check-label" for="exampleRadios1">Credit card</label>
      </div>
      <div class="form-check">
        <input class="form-check-input" type="radio" name="exampleRadios" id="exampleRadios2" value="option2">
        <label class="form-check-label" for="exampleRadios2">Debit card</label>
      </div>
      <div class="form-check disabled">
        <input class="form-check-input" type="radio" name="exampleRadios" id="exampleRadios3" value="option3">
        <label class="form-check-label" for="exampleRadios3">Paypal</label>
      </div>
      <div class="row">
          <div class="col-md-6 mb-3">
              <label for="cc-name">Name of card</label>
              <input type="text" class="form-control" id="cc-name">
          </div>
          <div class="col-md-6 mb-3">
            <label for="cc-name">Credit card number</label>
            <input type="text" class="form-control" id="cc-name">
        </div>
      </div>
      <div class="row">
        <div class="col-md-6 mb-3">
            <label for="cc-expiration">Expiration</label>
            <input type="text" class="form-control" id="cc-expiration">
        </div>
        <div class="col-md-6 mb-3">
            <label for="cc-expiration">CVV</label>
            <input type="text" class="form-control" id="cc-expiration">
        </div>
      </div>
    <div class="col-md-12 text-center mt-2"> 
        <p class="h2">Total Price {{ game_pk.price }}</p>
        <a type="submit" class="btn btn-primary" href="{% url 'afterpayment' game_pk.id %}">confirm</a>
    </div>
</div>

{% endblock  %}

projectgame/user/templates/user/profileuser.html
{% extends 'base.html' %}
{% block  content%}
{% load static %}



{% endblock  %}

projectgame/user/templates/user/usergame.html
<!DOCTYPE html>
{%load static %}
<html lang="en">

<head>
    <meta charset="UTF-8">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <link rel="stylesheet" href="https://stackpath.bootstrapcdn.com/bootstrap/4.4.1/css/bootstrap.min.css" integrity="sha384-Vkoo8x4CGsO3+Hhxv8T/Q5PaXtkKtu6ug5TOeNV6gBiFeWPGFN9MuhOf23Q9Ifjh" crossorigin="anonymous">
    <script src="https://code.jquery.com/jquery-3.4.1.slim.min.js" integrity="sha384-J6qa4849blE2+poT4WnyKhv5vZF5SrPo0iEjwBvKU7imGFAV0wwj1yYfoRSJoZ+n" crossorigin="anonymous"></script>
    <script src="https://cdn.jsdelivr.net/npm/popper.js@1.16.0/dist/umd/popper.min.js" integrity="sha384-Q6E9RHvbIyZFJoft+2mJbHaEWldlvI9IOYy5n3zV9zzTtmI3UksdQRVvoxMfooAo" crossorigin="anonymous"></script>
    <script src="https://stackpath.bootstrapcdn.com/bootstrap/4.4.1/js/bootstrap.min.js" integrity="sha384-wfSDF2E50Y2D1uUdj0O3uMBJnjuUD4Ih7YwaYd1iqfktj0Uod8GCExl3Og8ifwB6" crossorigin="anonymous"></script>
    <title>Document</title>
</head>

<body>
    

    
        <nav class="navbar navbar-light bg-dark justify-content-between">
            <a href= "{% url 'home' %}" >
            <p class="navbar-brand text-white mt-2"><img src="{% static '/img/game.png'%}" width="30" height="30" class="d-inline-block align-top" alt=""> Game Store</p>
            </a>
            <div class="text-right">       
                    <a href= "{% url 'home' %}"  class="btn btn-outline-light mr-sm-2 bg-muted">Home</a>
                    <a href= "{% url 'logout' %}"  class="btn btn-outline-light mr-sm-2 bg-muted">Logout</a>                
            </div>
        </nav>

<div class="container mb-5">
    <div class="row mt-5">
        <div class="col-md-10">
            <form action="" method="GET" class="form-inline">
                {% csrf_token %}
                <div class="form-group mx-sm-2 mb-2">
                    <input type="text" class="form-control" name="search" placeholder="Search...">
                </div>
            </form>
        </div>
        <div class="col-md-2">
            <p class="text-info">Fillter</p>
            <hr>
            {% for gt in gamety %}
            <form action="{% url 'filter' %}" method="GET" class="form-inline">
                <div class="checkbox">
                    <label><input type="checkbox" onclick="this.form.submit()" name="{{gt.type_name}}"><span
                            class="ml-1">{{gt.type_name}}</span></label>
                </div>
            </form>
            {% endfor %}
            </form>
        </div>
    </div>
    {% if usersearch %}
        {% for gm in game %}
        {% for im in image %}
        {% if im.game_id_id == game_id_id%}
        <div class="col-sm-3">
                <div class="card shadow rounded mt-2" style="width: 13rem; height: 40vh; display:inline-block;">
                    <img class="card-img-top" src="{{ im.img_url.url }}" alt="Card imagecap" />
                    <div class="card-body d-flex flex-column">
                        <p class="card-title text-center h6 font-weight-bolder">{{ gm.game_id.name }}</p>
                        <p class="card-title text-center h6 text-dark">Developer Team</p>
                        <small class="card-title text-center h6 text-dark">{{ gm.game_id.developer }}</small>
                    </div>
                </div>
        </div>
        {% endif %}
        {% endfor %}
        {% endfor %}    
    {% else %}
        <div class="row">
            <div class="card-deck">
                {% for gm in game %}
                {% for im in image %}
                {% if im.game_id_id == gm.game_id_id %}
                <a href="#">
                    <div class="card shadow rounded mt-5" style="width: 13rem; height: 35vh; display:inline-block;">
                        <img class="card-img-top" src="{{ im.img_url.url }}" alt="Card imagecap" />
                        <div class="card-body d-flex flex-column">
                            <p class="card-title text-center h6 font-weight-bolder">{{ gm.game_id.name }}</p>
                            <p class="card-title text-center h6 text-dark">Developer Team</p>
                            <small class="card-title text-center h6 text-dark">{{ gm.game_id.developer }}</small>
                        </div>
                    </div>
                </a>
                {% endif %}
                {% endfor %}
                {% endfor %}
            </div>
        </div>
    {% endif %}
</div>

</body>
</html>